// <auto-generated />
using System;
using GreenMeadows.Store.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GreenMeadows.Store.Api.Data.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260614104334_SwitchCatalogueToPhones")]
    partial class SwitchCatalogueToPhones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GreenMeadows.Store.Api.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("GreenMeadows.Store.Api.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CartId", "ProductId")
                        .IsUnique();

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("GreenMeadows.Store.Api.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "6.7\" flagship smartphone, 256GB, triple camera.",
                            ImageUrl = "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80&auto=format",
                            Name = "Aurora X1",
                            Price = 899.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "6.1\" mid-range smartphone, 128GB, dual camera.",
                            ImageUrl = "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80&auto=format",
                            Name = "Nimbus 5",
                            Price = 499.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "6.0\" budget smartphone, 64GB, long battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80&auto=format",
                            Name = "Pixela Lite",
                            Price = 299.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Description = "6.8\" pro smartphone, 512GB, 120Hz display.",
                            ImageUrl = "https://images.unsplash.com/photo-1605236453806-6ff36851218e?w=600&q=80&auto=format",
                            Name = "Quantum Pro",
                            Price = 1099.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Description = "5.4\" compact smartphone, 128GB, lightweight.",
                            ImageUrl = "https://images.unsplash.com/photo-1567581935884-3349723552ca?w=600&q=80&auto=format",
                            Name = "Eon Mini",
                            Price = 349.00m,
                            StockQuantity = 3
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Description = "6.5\" smartphone, 256GB, fast wireless charging.",
                            ImageUrl = "https://images.unsplash.com/photo-1580910051074-3eb694886505?w=600&q=80&auto=format",
                            Name = "Solis Z",
                            Price = 749.00m,
                            StockQuantity = 12
                        });
                });

            modelBuilder.Entity("GreenMeadows.Store.Api.Domain.CartItem", b =>
                {
                    b.HasOne("GreenMeadows.Store.Api.Domain.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenMeadows.Store.Api.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GreenMeadows.Store.Api.Domain.Cart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
